GET http://localhost:5019/games

###
GET http://localhost:5019/games/6

###
POST http://localhost:5019/games
Content-Type: application/json

{
  "name": "COC",
  "genreId": 2,
  "price": 57.99,
  "releasedDate": "2026-08-14"
}

###
PUT http://localhost:5019/games/6
Content-Type: application/json

{
  "name": "FIFA Mobile 27",
  "genreId": 5,
  "price": 90.99,
  "releasedDate": "2026-08-13"
}

###
DELETE http://localhost:5019/games/7
